# Configuración principal para el framework pre-commit
repos:
  # --- Formateador de Código ---
  - repo: https://github.com/psf/black
    rev: 24.4.2 
    hooks:
      - id: black
        language_version: python3.12

  # --- Linter ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # --- Ordenar Importaciones ---
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"] # Asegura compatibilidad con Black

  # --- VALIDACIÓN DE MENSAJES DE COMMIT ---
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg] 
        # args: 
        #   - --types=feat,fix,docs,style,test
        #   - --max-header-length=70